"""Renders reports/VALIDATION_REPORT.md from the computed metrics.

Every number in the report is produced by the pipeline at render time. Nothing
is transcribed by hand, so the report cannot drift away from the artifacts.
"""

from __future__ import annotations

import datetime as dt
from collections.abc import Sequence
from typing import Any

from . import config as cfg
from . import statistics as st
from .claims import CLAIMS, Disposition
from .legacy import reproduce_legacy_final_data
from .metrics import SeriesMetrics, peak_dispersion, review_categories
from .transform import Panel


def _fmt(value: float | None, places: int = 3) -> str:
    if value is None:
        return "n/a"
    if isinstance(value, float) and value != value:  # NaN
        return "n/a"
    return f"{value:.{places}f}"


def _p(value: float) -> str:
    if value != value:
        return "n/a"
    return "<0.0001" if value < 0.0001 else f"{value:.4f}"


def _numeric(row: dict[str, object], key: str) -> float:
    """Read a numeric cell out of a legacy replay row."""
    value = row[key]
    if isinstance(value, (int, float)) and not isinstance(value, bool):
        return float(value)
    raise TypeError(f"column {key!r} is not numeric: {value!r}")


def legacy_correlations() -> dict[str, dict[str, float]]:
    """Recompute correlations on the ORIGINAL (legacy) dataset.

    Uses the byte-identical legacy replay, so the "before" column of the
    before/after table is generated rather than transcribed. Reproduces the
    original alignment (+1 week), the rounded $/litre variable and the 29-row
    truncated panel.
    """
    result = reproduce_legacy_final_data(
        cfg.OIL_RAW_CSV, cfg.PROCESSED_DIR, cfg.COUNTRIES, cfg.WORLDWIDE
    )
    price = [_numeric(row, "Price($)/Litre") for row in result.rows]

    out: dict[str, dict[str, float]] = {}
    for series in cfg.ALL_SERIES:
        values = [_numeric(row, series.legacy_column) for row in result.rows]
        pearson = st.pearson(price, values)
        spearman = st.spearman(price, values)
        out[series.id] = {
            "n": float(len(values)),
            "pearson_r": pearson.coefficient,
            "pearson_p": pearson.p_value,
            "spearman_rho": spearman.coefficient,
        }
    return out


def render_validation_report(
    panel: Panel,
    series_metrics: Sequence[SeriesMetrics],
    oil_stats: dict[str, Any],
    *,
    legacy_matches: bool,
    legacy_rows: int,
) -> str:
    by_id = {m.series.id: m for m in series_metrics}
    countries = [m for m in series_metrics if m.series.is_country]
    worldwide = by_id["worldwide"]
    dispersion = peak_dispersion(countries)
    reviews = review_categories({m.series.id: m for m in countries})
    before = legacy_correlations()

    lines: list[str] = []
    add = lines.append

    add("# Analytical Validation Report")
    add("")
    add(
        "Generated by `python -m pipeline.build --report`. Every figure below is computed "
        "at render time from the committed source data; none is transcribed by hand."
    )
    add("")

    # ---------------------------------------------------------------- coverage
    add("## 1. Dataset coverage after correction")
    add("")
    add("| Quantity | Value |")
    add("| --- | --- |")
    add(f"| Google Trends observations per series | **{panel.trends_weeks}** |")
    add(f"| Weekly oil observations in range | **{panel.oil_weeks}** |")
    add(
        f"| Analytical pairs at primary lag ({cfg.PRIMARY_LAG_WEEKS}) | **{worldwide.primary.n}** |"
    )
    add(f"| Observation window | {panel.rows[0].week_start} to {panel.rows[-1].week_start} |")
    add(
        "| Weeks with no oil observation | "
        + (", ".join(d.isoformat() for d in panel.weeks_without_oil) or "none")
        + " |"
    )
    add(
        "| Partial oil weeks (<5 trading days) | "
        + (", ".join(d.isoformat() for d in panel.partial_weeks) or "none")
        + " |"
    )
    add(
        f"| Legacy replay byte-identical to `final_data.csv` | "
        f"**{'yes' if legacy_matches else 'NO'}** ({legacy_rows} rows) |"
    )
    add("")
    add(
        f"The ingestion fix recovers the two observations the original `skiprows=2` bug "
        f"destroyed, taking each Trends series from 29 usable weeks to "
        f"**{panel.trends_weeks}**. The joined panel at lag 0 contains "
        f"{worldwide.primary.n} pairs because the oil extract ends "
        f"{oil_stats['last_week']}, one week before the final Trends week "
        f"({panel.rows[-1].week_start}). That week is retained in `panel.json` with a null "
        f"oil value rather than dropped."
    )
    add("")

    # ------------------------------------------------------------------- oil
    add("## 2. Oil price series (Brent crude, FRED DCOILBRENTEU)")
    add("")
    add("| Quantity | Value |")
    add("| --- | --- |")
    add(
        f"| Weekly mean range | ${_fmt(oil_stats['min_usd_per_barrel'], 2)} – "
        f"${_fmt(oil_stats['max_usd_per_barrel'], 2)} per barrel |"
    )
    add(f"| Peak week | {oil_stats['max_week']} |")
    add(f"| Peak in $/litre (crude, not pump price) | ${_fmt(oil_stats['max_usd_per_litre'], 4)} |")
    add(f"| Mean | ${_fmt(oil_stats['mean_usd_per_barrel'], 2)} per barrel |")
    add(
        f"| Regime onset (largest week-over-week rise) | {panel.regime.onset_week} "
        f"({panel.regime.onset_pct_change * 100:+.1f}%) |"
    )
    add(
        f"| Baseline weeks / elevated weeks | {len(panel.regime.baseline_weeks)} / "
        f"{len(panel.regime.elevated_weeks)} |"
    )
    add(
        f"| Baseline max / elevated min | ${_fmt(panel.regime.baseline_max_usd_per_barrel, 2)} / "
        f"${_fmt(panel.regime.elevated_min_usd_per_barrel, 2)} per barrel |"
    )
    add(f"| Regimes separated in level | {'yes' if panel.regime.separated else 'no'} |")
    add(
        "| Weeks containing forward-filled holidays | "
        + (
            ", ".join(
                f"{w['week_start']} ({w['imputed_days']}d)"
                for w in oil_stats["weeks_with_imputed_days"]
            )
            or "none"
        )
        + " |"
    )
    add("")
    add(
        f"The elevated regime occupies only **{len(panel.regime.elevated_weeks)} of "
        f"{panel.oil_weeks} weeks**. Every correlation below is therefore driven by a short "
        f"episode at the top of the price range, which is what the sensitivity section "
        f"quantifies."
    )
    add("")

    # ------------------------------------------------------- country metrics
    add("## 3. Country metrics (primary specification)")
    add("")
    add(
        f"Contemporaneous alignment (lag = {cfg.PRIMARY_LAG_WEEKS}), oil in $/litre of crude, "
        f"{cfg.CONFIDENCE_LEVEL:.0%} percentile bootstrap "
        f"({cfg.BOOTSTRAP_ITERATIONS:,} iterations, seed {cfg.BOOTSTRAP_SEED})."
    )
    add("")
    add("| Country | Pearson r | p | Spearman ρ | n | 95% CI | Peak week | Classification |")
    add("| --- | ---: | ---: | ---: | ---: | :---: | --- | --- |")
    for m in countries:
        p = m.primary
        add(
            f"| {m.series.label} | {_fmt(p.pearson_r)} | {_p(p.pearson_p)} | "
            f"{_fmt(p.spearman_rho)} | {p.n} | "
            f"[{_fmt(p.bootstrap_ci.low, 2)}, {_fmt(p.bootstrap_ci.high, 2)}] | "
            f"{m.profile.peak_week} | {m.evidence_group.replace('_', ' ')} |"
        )
    add("")
    add("### Worldwide")
    add("")
    wp = worldwide.primary
    add("| Pearson r | p | Spearman ρ | n | 95% CI (bootstrap) | 95% CI (Fisher z) | Peak week |")
    add("| ---: | ---: | ---: | ---: | :---: | :---: | --- |")
    add(
        f"| {_fmt(wp.pearson_r)} | {_p(wp.pearson_p)} | {_fmt(wp.spearman_rho)} | {wp.n} | "
        f"[{_fmt(wp.bootstrap_ci.low, 2)}, {_fmt(wp.bootstrap_ci.high, 2)}] | "
        f"[{_fmt(wp.fisher_ci.low, 2)}, {_fmt(wp.fisher_ci.high, 2)}] | "
        f"{worldwide.profile.peak_week} |"
    )
    add("")

    # --------------------------------------------- specification checks
    add("## 4. Specification checks: is the level correlation more than a shared trend?")
    add("")
    add(
        "Both variables rise across the observed window, so a correlation in levels is "
        "expected whether or not the two are related. Three specifications are reported "
        "and their disagreement is treated as the finding rather than resolved by picking "
        "a favourite:"
    )
    add("")
    add(
        "- **levels** — weekly values as published (the primary specification)\n"
        "- **first differences** — week-over-week changes; removes any shared trend, but is "
        "noisy and has low power if the true relationship operates on levels\n"
        "- **linear detrended** — residuals after removing a straight-line time trend; "
        "note this models a flat-then-step price path poorly, so it does not fully remove "
        "the confound either"
    )
    add("")
    add(
        "| Series | Oil vs time r | Interest vs time r | Levels r (p) | "
        "First-diff r (p) | Detrended r (p) | Agreement |"
    )
    add("| --- | ---: | ---: | ---: | ---: | ---: | --- |")
    for m in series_metrics:
        diag = m.trend

        def spec_cell(spec_id: str, diagnostics: Any = diag) -> str:
            spec = diagnostics.by_id(spec_id)
            if spec is None:
                return "n/a"
            mark = "**" if spec.significant else ""
            return f"{mark}{_fmt(spec.pearson_r)}{mark} ({_p(spec.pearson_p)})"

        add(
            f"| {m.series.label} | {_fmt(diag.oil_vs_time_r, 2)} | "
            f"{_fmt(diag.interest_vs_time_r, 2)} | {spec_cell('levels')} | "
            f"{spec_cell('first_differences')} | {spec_cell('linear_detrended')} | "
            f"{diag.agreement.replace('_', ' ')} |"
        )
    add("")
    add("Bold marks significance at α = 0.05.")
    add("")

    differencing_survivors = [
        m.series.label
        for m in series_metrics
        if (spec := m.trend.by_id("first_differences")) is not None and spec.significant
    ]
    add(
        f"**No series survives first differencing** "
        f"({len(differencing_survivors)} of {len(series_metrics)} significant at α = 0.05"
        + (f": {', '.join(differencing_survivors)}" if differencing_survivors else "")
        + "). Week-to-week changes in crude prices and EV search interest show no "
        "detectable relationship in any market. Linear detrending disagrees for several "
        "series, which is expected given the step-shaped price path, so the two checks "
        "bound rather than settle the question."
    )
    add("")
    add(
        "This is the single most important limitation in the analysis. Every significant "
        "level correlation below is classified `level_only_association`, and no series "
        "reaches the `robust_positive_association` classification. The honest reading is "
        "that crude prices and EV interest both rose over these seven months, and this "
        "dataset cannot separate a genuine relationship from two trends that happened to "
        "coincide."
    )
    add("")

    # ------------------------------------------------- scale-free comparison
    add("## 5. Valid cross-country comparison (scale-free metrics only)")
    add("")
    add(
        "Interest levels are **not** comparable between series because each Google Trends "
        "export is rescaled to its own maximum. The metrics below are ratios or timings "
        "within a single series, so the per-series scale factor cancels."
    )
    add("")
    add(
        "| Country | r | Baseline→peak % | Baseline→elevated % | Peak week | "
        "Peak vs oil peak | Robustness |"
    )
    add("| --- | ---: | ---: | ---: | --- | ---: | --- |")
    for m in sorted(countries, key=lambda x: x.primary.pearson_r, reverse=True):
        pr = m.profile
        add(
            f"| {m.series.label} | {_fmt(m.primary.pearson_r)} | "
            f"{_fmt(pr.baseline_to_peak_pct_change, 1)}% | "
            f"{_fmt(pr.baseline_to_elevated_pct_change, 1)}% | {pr.peak_week} | "
            f"{pr.peak_lag_weeks:+d}w | {m.robustness} |"
        )
    add("")

    # ------------------------------------------------------------ dispersion
    add("## 6. Peak timing: the 'synchronised peak' claim")
    add("")
    add(f"- Distinct peak weeks across the five countries: **{dispersion.distinct_weeks}**")
    add(
        f"- Distinct calendar months: **{len(dispersion.distinct_months)}** "
        f"({', '.join(dispersion.distinct_months)})"
    )
    add(f"- Span between earliest and latest peak: **{dispersion.span_weeks} weeks**")
    add(
        "- Synchronised within a single month: "
        f"**{'yes' if dispersion.synchronised_within_one_month else 'NO'}**"
    )
    add("")
    add("| Country | Peak week | Regime at peak |")
    add("| --- | --- | --- |")
    onset = panel.regime.onset_week
    for m in countries:
        week = m.profile.peak_week
        add(f"| {m.series.label} | {week} | {'elevated' if week >= onset else 'baseline'} |")
    add("")
    add(
        f"The original claim of a synchronised peak across five countries in a single month "
        f"is **not supported**. Peaks fall in {len(dispersion.distinct_months)} different "
        f"months, and the peaks occurring before {onset} predate the price-regime onset "
        f"entirely, so they cannot be a response to it."
    )
    add("")

    # ------------------------------------------------------------------ lag
    add("## 7. Lag analysis (exploratory)")
    add("")
    add(
        f"Lag *k* pairs oil from week *t − k* with interest at week *t*; positive *k* means "
        f"oil leads. Window {cfg.LAG_MIN_WEEKS} to {cfg.LAG_MAX_WEEKS} weeks. "
        "**Exploratory only**: the best lag is selected post hoc and its p-value is not "
        "corrected for the multiple comparisons implied by scanning a window. The original "
        "notebook's accidental alignment corresponds to k = +1."
    )
    add("")
    lags = sorted({p.lag_weeks for m in series_metrics for p in m.lag_points})
    add("| Series | " + " | ".join(f"k={k:+d}" for k in lags) + " | Best k |")
    add("| --- | " + " | ".join("---:" for _ in lags) + " | :---: |")
    for m in series_metrics:
        cells = {p.lag_weeks: p.pearson_r for p in m.lag_points}
        row = " | ".join(_fmt(cells.get(k), 2) if k in cells else "–" for k in lags)
        best = f"{m.best.lag_weeks:+d}" if m.best else "none"
        add(f"| {m.series.label} | {row} | **{best}** |")
    add("")

    # ---------------------------------------------------------- sensitivity
    add("## 8. Sensitivity")
    add("")
    add("### 8.1 Leave-one-out")
    add("")
    add("| Series | r | min r | max r | max │Δr│ | Most influential week | Sign flips |")
    add("| --- | ---: | ---: | ---: | ---: | --- | :---: |")
    for m in series_metrics:
        loo = m.sensitivity_result.leave_one_out
        worst = loo.per_observation[loo.most_influential_index]
        add(
            f"| {m.series.label} | {_fmt(loo.baseline_r)} | {_fmt(loo.min_r)} | "
            f"{_fmt(loo.max_r)} | {_fmt(loo.max_abs_delta)} | {worst['label']} | "
            f"{'YES' if loo.sign_flips else 'no'} |"
        )
    add("")
    add("### 8.2 Specification variants")
    add("")
    add("| Series | Variant | n | r | p | Δr vs primary |")
    add("| --- | --- | ---: | ---: | ---: | ---: |")
    for m in series_metrics:
        for v in m.sensitivity_result.variants:
            if not v.computable:
                add(f"| {m.series.label} | {v.id} | {v.n} | not computable | – | – |")
                continue
            add(
                f"| {m.series.label} | {v.id} | {v.n} | {_fmt(v.pearson_r)} | "
                f"{_p(v.pearson_p)} | {_fmt(v.delta_vs_primary)} |"
            )
    add("")

    # -------------------------------------------------------- before / after
    add("## 9. Before vs after correction")
    add("")
    add(
        "'Before' recomputes correlations on the byte-identical legacy replay: 29 rows, "
        "$/litre rounded to 2 decimals, and the accidental +1-week alignment. 'After' is the "
        "corrected primary specification. Both columns are generated by code."
    )
    add("")
    add("| Series | r before | r after | Δr | ρ before | ρ after | n before | n after |")
    add("| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |")
    for m in series_metrics:
        b = before[m.series.id]
        add(
            f"| {m.series.label} | {_fmt(b['pearson_r'])} | {_fmt(m.primary.pearson_r)} | "
            f"{_fmt(m.primary.pearson_r - b['pearson_r'])} | {_fmt(b['spearman_rho'])} | "
            f"{_fmt(m.primary.spearman_rho)} | {int(b['n'])} | {m.primary.n} |"
        )
    add("")
    add("Four independent changes contribute to these deltas:")
    add("")
    add("1. **Ingestion fix** — two destroyed observations recovered per series.")
    add("2. **Alignment fix** — contemporaneous weeks instead of an accidental +1-week lag.")
    add("3. **Precision fix** — $/litre no longer rounded to 2 decimals before analysis.")
    add(
        f"4. **Unit constant** — {cfg.LITRES_PER_BARREL} litres per barrel instead of "
        f"{cfg.LEGACY_LITRES_PER_BARREL}. This one is analytically inert: a positive linear "
        "rescale leaves every correlation unchanged and affects only displayed values."
    )
    add("")

    # ---------------------------------------------------- category review
    add("## 10. Executive-summary categories, re-evaluated")
    add("")
    add("| Category | Original members | Data-supported | Unsupported | Verdict |")
    add("| --- | --- | --- | --- | --- |")

    def labels(series_ids: Sequence[str]) -> str:
        return ", ".join(by_id[sid].series.label for sid in series_ids) or "—"

    for r in reviews:
        add(
            f"| {r.original_title} | {labels(r.original_members)} | "
            f"{labels(r.data_supported_members)} | {labels(r.unsupported_members)} | "
            f"**{r.verdict.replace('_', ' ')}** |"
        )
    add("")
    add(
        "Every category is additionally marked `requires_external_evidence = true`: the "
        "category *names* assert mechanisms — subsidy buffering, proactive policy response, "
        "market maturity — and a crude price series plus a search index cannot establish a "
        "mechanism. The statistical pattern and the explanation are separate claims."
    )
    add("")

    # -------------------------------------------------------------- claims
    add("## 11. Claim dispositions")
    add("")
    counts: dict[str, int] = {}
    for claim in CLAIMS:
        counts[claim.disposition] = counts.get(claim.disposition, 0) + 1
    add("| Disposition | Count |")
    add("| --- | ---: |")
    for disposition, count in sorted(counts.items()):
        add(f"| {disposition.replace('_', ' ')} | {count} |")
    add("")
    needs_citation = [c for c in CLAIMS if c.disposition == Disposition.REQUIRES_CITATION]
    add(
        f"**{len(needs_citation)} claims require a citation before they may be published as "
        f"fact.** Each is recorded in `claims.json` with an empty `sources` array and "
        f"`publishable_as_fact: false`:"
    )
    add("")
    for claim in needs_citation:
        add(f"- `{claim.id}` — {claim.origin}")
    add("")

    # --------------------------------------------------------- limitations
    add("## 12. Limitations that must be disclosed")
    add("")
    add(
        f"1. **Sample size.** {worldwide.primary.n} weekly pairs. Every interval is wide and "
        "every coefficient is imprecise."
    )
    add(
        f"2. **Regime imbalance.** Only {len(panel.regime.elevated_weeks)} weeks sit in the "
        f"elevated-price regime, against {len(panel.regime.baseline_weeks)} baseline weeks. "
        "The oil variable has almost no variation outside that short episode."
    )
    add(
        "3. **No cross-series level comparison is possible.** Each Trends export is rescaled "
        "to its own maximum. Statements ranking markets by interest level are unavailable "
        "from these files at any level of effort."
    )
    add(
        "4. **Correlation only.** No confounder is measured or controlled: seasonality, "
        "model launches, news volume, advertising, policy announcements. No causal claim is "
        "supportable."
    )
    add(
        "5. **Crude, not retail.** The price variable is a global crude benchmark. Consumers "
        "respond to pump prices, which differ by country through tax and subsidy regimes and "
        "are absent from this dataset."
    )
    add(
        f"6. **One partial week.** The oil week beginning "
        f"{', '.join(d.isoformat() for d in panel.partial_weeks) or 'n/a'} rests on fewer "
        "than five trading days and is flagged in every artifact."
    )
    add(
        "7. **Trends provenance is incomplete.** The original project did not record the exact "
        "query terms, category filter or retrieval dates for the six exports, so the Google "
        "Trends half of this analysis is not fully reproducible from source."
    )
    add(
        "8. **Search interest is not adoption.** The dependent variable measures searching, "
        "not buying."
    )
    add("")
    add("---")
    add("")
    add(
        f"Pipeline `{cfg.REGIME_RULE}` regime rule · primary lag {cfg.PRIMARY_LAG_WEEKS} · "
        f"bootstrap seed {cfg.BOOTSTRAP_SEED} · "
        f"report rendered from source data on {dt.date.today().isoformat()}"
    )
    add("")

    return "\n".join(lines)
