/**
 * TypeScript contract for the analytical artifacts generated by `pipeline/`.
 *
 * These types are modelled from the ACTUAL emitted JSON in
 * `src/data/generated/`, not from the Python source and not from assumption.
 * Every nullable field below is nullable because the pipeline really can emit
 * `null` there:
 *
 *   - `PanelRow.oil`                     null where the oil extract stops short
 *                                        of the Trends grid (week 2026-03-29)
 *   - `PanelRow.regime`                  null exactly when `oil` is null
 *   - `SeriesMetrics.bestLag`            null when no non-negative lag is
 *                                        positive (currently Indonesia)
 *   - `SensitivityVariant.pearsonR/…`    null when `computable` is false
 *   - `SensitivityVariant.reason`        null when `computable` is true
 *   - `Claim.suggestedStatement`         null for claims with no draft wording
 *   - `DataSource.seriesId`              null for sources with no series id
 *
 * NAMING: JSON uses snake_case (Python). These interfaces keep snake_case so
 * the contract is a literal mirror of the artifact. Renaming at this boundary
 * would create two vocabularies for the same field and make the JSON harder to
 * cross-reference during review.
 *
 * HARD RULE: nothing in the presentation layer may compute a statistic. Every
 * numeric field here is READ from the artifact. See `docs/frontend-data-contract.md`.
 */

// ---------------------------------------------------------------------------
// Identifiers and enumerations
// ---------------------------------------------------------------------------

/** The five analysed markets. `us` is canonical; never "usa"/"america". */
export type CountryId = "indonesia" | "malaysia" | "norway" | "singapore" | "us";

/** All interest series, including the worldwide aggregate. */
export type SeriesId = CountryId | "worldwide";

export const COUNTRY_IDS: readonly CountryId[] = [
  "indonesia",
  "malaysia",
  "norway",
  "singapore",
  "us",
];

export const SERIES_IDS: readonly SeriesId[] = [...COUNTRY_IDS, "worldwide"];

/** Price regime for a week. Null when the week has no oil observation. */
export type Regime = "baseline" | "elevated";

/** Conventional |r| bands. A labelling aid, not a statistical test. */
export type StrengthLabel = "negligible" | "weak" | "moderate" | "strong" | "very_strong";

export type Direction = "positive" | "negative";

export type Significance = "significant" | "not_significant";

export type Robustness = "fragile" | "moderate" | "robust";

/**
 * Measured statistical pattern. Carries no mechanism and no explanation.
 * `robust_*` requires the association to survive first differencing; no series
 * currently reaches it.
 */
export type EvidenceGroup =
  | "no_detectable_association"
  | "inconclusive"
  | "level_only_association"
  | "robust_positive_association"
  | "robust_negative_association";

/** Specification-check identifiers, in reporting order. */
export type SpecificationId = "levels" | "first_differences" | "linear_detrended";

/** Whether the three specifications agree. */
export type SpecificationAgreement =
  "consistent" | "significance_disagreement" | "sign_disagreement";

export type SensitivityVariantId =
  "exclude_partial_weeks" | "baseline_regime_only" | "elevated_regime_only" | "rank_based";

/**
 * Caveat codes, not sentences. The analytical layer states what is limiting;
 * the content layer owns the wording.
 */
export type CaveatCode =
  | "small_sample"
  | "few_elevated_observations"
  | "includes_partial_week"
  | "ci_includes_zero"
  | "loo_sign_flip"
  | "leverage_dependent"
  | "not_significant"
  | "series_local_scale"
  | "loses_significance_without_elevated_regime"
  | "no_short_run_comovement"
  | "shared_trend_confound_possible"
  | "specification_sensitive"
  | "regime_sensitive"
  | "negative_lag_maximum";

export type ClaimStatus =
  | "supported_by_data"
  | "overstated_relative_to_data"
  | "contradicted_by_data"
  | "invalid_method"
  | "external_unverifiable_from_dataset"
  | "beyond_data_window"
  | "describes_work_not_present";

export type ClaimDisposition = "retain" | "rewrite" | "remove" | "requires_citation";

export type CategoryVerdict = "supported" | "partially_supported" | "not_supported";

/** ISO calendar date, `YYYY-MM-DD`. Always a Sunday for week keys. */
export type IsoDate = string;

// ---------------------------------------------------------------------------
// panel.json
// ---------------------------------------------------------------------------

export interface OilWeek {
  /** Rounded for display (2dp). */
  readonly brent_usd_per_barrel: number;
  /** Rounded for display (4dp). */
  readonly brent_usd_per_litre: number;
  /** Full precision. Use this for plotting. */
  readonly brent_usd_per_barrel_exact: number;
  /** Full precision. Use this for plotting. */
  readonly brent_usd_per_litre_exact: number;
  /** Daily source rows contributing to the weekly mean. 5 = complete week. */
  readonly trading_days: number;
  /** How many of those rows were forward-filled market holidays. */
  readonly imputed_days: number;
  /** True when `trading_days < 5`. Must be visually distinguished. */
  readonly is_partial_week: boolean;
  readonly min_usd_per_barrel: number;
  readonly max_usd_per_barrel: number;
}

export interface PanelRow {
  readonly week_start: IsoDate;
  readonly week_end: IsoDate;
  readonly regime: Regime | null;
  /** Null where the oil extract does not reach this Trends week. */
  readonly oil: OilWeek | null;
  /** Interest score per series, 0-100, each scaled to its OWN peak. */
  readonly interest: Readonly<Record<SeriesId, number>>;
}

export interface Coverage {
  readonly trends_weeks: number;
  readonly oil_weeks: number;
  readonly first_week: IsoDate;
  readonly last_week: IsoDate;
  readonly weeks_without_oil: readonly IsoDate[];
  readonly partial_weeks: readonly IsoDate[];
}

export interface PanelArtifact {
  readonly schema_version: string;
  /** Human-readable unit descriptions, for rendering methodology copy. */
  readonly units: {
    readonly brent_usd_per_barrel: string;
    readonly brent_usd_per_litre: string;
    readonly interest: string;
  };
  readonly conventions: {
    readonly week_key: string;
    readonly oil_aggregation: string;
    readonly missing_daily_values: string;
    readonly rows_without_oil: string;
  };
  readonly coverage: Coverage;
  readonly rows: readonly PanelRow[];
}

// ---------------------------------------------------------------------------
// countries.json
// ---------------------------------------------------------------------------

export interface SeriesRegistryEntry {
  readonly id: SeriesId;
  /** Display label. The UI must use this and never invent its own. */
  readonly label: string;
  readonly short: string;
  readonly is_country: boolean;
  readonly source_file: string;
  readonly legacy_column: string;
}

/**
 * Machine-readable statement of what may and may not be compared across
 * series. Present so the presentation layer cannot re-introduce the invalid
 * cross-market level comparison the original project made.
 */
export interface Comparability {
  readonly trends_normalisation: string;
  readonly explanation: string;
  /** Metrics that are ratios or timings within one series: safe to compare. */
  readonly scale_free_metrics: readonly string[];
  /** Metrics on a per-series scale: NEVER compare these across series. */
  readonly series_local_metrics: readonly string[];
  /** Comparisons the UI must refuse to render. */
  readonly forbidden_comparisons: readonly string[];
  readonly remedy: string;
}

export interface CountriesArtifact {
  readonly schema_version: string;
  readonly series: readonly SeriesRegistryEntry[];
  readonly comparability: Comparability;
}

// ---------------------------------------------------------------------------
// metrics.json
// ---------------------------------------------------------------------------

export interface Interval {
  readonly low: number;
  readonly high: number;
  readonly level: number;
  readonly method: string;
}

export interface LinearFit {
  readonly slope: number;
  readonly intercept: number;
  readonly r_squared: number;
  readonly slope_stderr: number;
  readonly n: number;
}

export interface CorrelationBundle {
  readonly lag_weeks: number;
  readonly n: number;
  readonly pearson_r: number;
  readonly pearson_p: number;
  readonly spearman_rho: number;
  readonly spearman_p: number;
  readonly bootstrap_ci: Interval;
  readonly fisher_ci: Interval;
  /** OLS fit in $/litre. Emitted so the UI never computes a regression line. */
  readonly fit: LinearFit;
  readonly significant_at_alpha: boolean;
  readonly alpha: number;
  readonly ci_includes_zero: boolean;
  readonly strength_label: StrengthLabel;
  readonly direction: Direction;
  readonly includes_partial_week: boolean;
}

export interface LagPoint {
  readonly lag_weeks: number;
  readonly n: number;
  readonly pearson_r: number;
  readonly pearson_p: number;
  readonly spearman_rho: number;
}

export interface Specification {
  readonly id: SpecificationId;
  readonly description: string;
  readonly n: number;
  readonly pearson_r: number;
  readonly pearson_p: number;
  readonly significant_at_alpha: boolean;
}

export interface TrendDiagnostics {
  readonly oil_vs_time_r: number;
  readonly interest_vs_time_r: number;
  readonly both_series_trend_same_direction: boolean;
  readonly specifications: readonly Specification[];
  readonly agreement: SpecificationAgreement;
  readonly note: string;
}

export interface LeaveOneOutObservation {
  readonly index: number;
  /** ISO week of the omitted observation. */
  readonly label: IsoDate | null;
  readonly r_without: number;
  readonly delta: number;
}

export interface LeaveOneOut {
  readonly baseline_r: number;
  readonly min_r: number;
  readonly max_r: number;
  readonly max_abs_delta: number;
  readonly most_influential_index: number;
  readonly sign_flips: boolean;
  readonly per_observation: readonly LeaveOneOutObservation[];
}

export interface SensitivityVariant {
  readonly id: SensitivityVariantId;
  readonly description: string;
  readonly n: number;
  /** Null when `computable` is false. */
  readonly pearson_r: number | null;
  /** Null when `computable` is false. */
  readonly pearson_p: number | null;
  /** Null when `computable` is false. */
  readonly delta_vs_primary: number | null;
  readonly computable: boolean;
  /** Explanation when `computable` is false; null otherwise. Render it. */
  readonly reason: string | null;
}

export interface Sensitivity {
  readonly leave_one_out: LeaveOneOut;
  readonly variants: readonly SensitivityVariant[];
}

/** Metrics on this series' own 0-100 scale. NOT comparable across series. */
export interface SeriesLocalProfile {
  readonly mean_interest: number;
  readonly median_interest: number;
  readonly min_interest: number;
  readonly peak_value: number;
  readonly baseline_mean_interest: number;
  readonly elevated_mean_interest: number;
  readonly _comparable_across_series: false;
}

/** Ratios and timings within one series. Safe to compare across series. */
export interface ScaleFreeProfile {
  readonly peak_week: IsoDate;
  readonly peak_week_ties: number;
  readonly baseline_to_peak_pct_change: number;
  readonly baseline_to_elevated_pct_change: number;
  /** Weeks between the oil peak week and this series' peak. + = after oil. */
  readonly peak_lag_weeks: number;
  readonly _comparable_across_series: true;
}

export interface InterestProfile {
  readonly series_local: SeriesLocalProfile;
  readonly scale_free: ScaleFreeProfile;
}

export interface Classification {
  readonly strength: StrengthLabel;
  readonly direction: Direction;
  readonly significance: Significance;
  readonly robustness: Robustness;
  readonly evidence_group: EvidenceGroup;
  readonly caveats: readonly CaveatCode[];
}

export interface SeriesMetrics {
  readonly id: SeriesId;
  readonly label: string;
  readonly short: string;
  readonly is_country: boolean;
  readonly primary: CorrelationBundle;
  readonly lag_profile: readonly LagPoint[];
  /** Null when no non-negative lag has a positive coefficient. */
  readonly best_lag: LagPoint | null;
  /** True when the unrestricted lag maximum sits at a negative lag. */
  readonly unrestricted_lag_maximum_is_negative: boolean;
  readonly trend_diagnostics: TrendDiagnostics;
  readonly sensitivity: Sensitivity;
  readonly profile: InterestProfile;
  readonly classification: Classification;
}

export interface OilStatistics {
  readonly weeks: number;
  readonly first_week: IsoDate;
  readonly last_week: IsoDate;
  readonly mean_usd_per_barrel: number;
  readonly median_usd_per_barrel: number;
  readonly min_usd_per_barrel: number;
  readonly min_week: IsoDate;
  readonly max_usd_per_barrel: number;
  readonly max_week: IsoDate;
  readonly max_usd_per_litre: number;
  readonly total_pct_change_first_to_max: number;
  readonly partial_weeks: readonly IsoDate[];
  readonly weeks_with_imputed_days: readonly {
    readonly week_start: IsoDate;
    readonly imputed_days: number;
  }[];
}

export interface RegimeSummary {
  readonly rule: string;
  readonly onset_week: IsoDate;
  readonly onset_pct_change: number;
  readonly baseline_weeks: number;
  readonly elevated_weeks: number;
  readonly baseline_max_usd_per_barrel: number;
  readonly elevated_min_usd_per_barrel: number;
  /** False means the split must NOT be presented as a distinct regime. */
  readonly regimes_separated: boolean;
}

export interface PeakDispersion {
  readonly peaks: Readonly<Record<CountryId, IsoDate>>;
  readonly distinct_weeks: number;
  readonly distinct_months: readonly string[];
  readonly span_weeks: number;
  /** Currently false. The original "synchronised peak" claim is not supported. */
  readonly synchronised_within_one_month: boolean;
}

/**
 * Full analytical configuration, as emitted in `metrics.configuration`.
 *
 * NOTE: `manifest.analytical_configuration` is a DIFFERENT, smaller shape --
 * see `ManifestAnalyticalConfiguration`. The two are not interchangeable, and
 * modelling them as one type is a mistake the validator will catch.
 */
export interface AnalyticalConfiguration {
  readonly primary_lag_weeks: number;
  readonly lag_window_weeks: readonly number[];
  readonly min_pairs_for_lag: number;
  readonly confidence_level: number;
  readonly bootstrap_iterations: number;
  readonly bootstrap_seed: number;
  readonly significance_alpha: number;
  readonly litres_per_barrel: number;
  readonly include_partial_weeks_in_primary: boolean;
  readonly regime_rule: string;
  readonly lag_sign_convention: string;
}

/**
 * Reproducibility subset recorded in `manifest.analytical_configuration`.
 *
 * Deliberately not identical to `AnalyticalConfiguration`: the manifest records
 * what is needed to reproduce a build (including `trends_normalisation`) and
 * omits reporting-only settings such as `significance_alpha`.
 */
export interface ManifestAnalyticalConfiguration {
  readonly primary_lag_weeks: number;
  readonly lag_window_weeks: readonly number[];
  readonly confidence_level: number;
  readonly bootstrap_iterations: number;
  readonly bootstrap_seed: number;
  readonly litres_per_barrel: number;
  readonly regime_rule: string;
  readonly trends_normalisation: string;
}

export interface GlobalMetrics {
  readonly oil: OilStatistics;
  readonly regime: RegimeSummary;
  readonly peak_dispersion: PeakDispersion;
  readonly worldwide: SeriesMetrics | null;
  /** Countries grouped by measured pattern. Keys are a subset of EvidenceGroup. */
  readonly evidence_groups: Readonly<Partial<Record<EvidenceGroup, readonly CountryId[]>>>;
}

/**
 * Re-evaluation of the original executive categories against the corrected
 * metrics. `requires_external_evidence` is always true: the category names
 * assert mechanisms a price series and a search index cannot establish.
 */
export interface CategoryReview {
  readonly id: string;
  readonly original_title: string;
  readonly original_members: readonly CountryId[];
  readonly data_supported_members: readonly CountryId[];
  readonly unsupported_members: readonly CountryId[];
  readonly verdict: CategoryVerdict;
  readonly requires_external_evidence: boolean;
  readonly basis: string;
}

export interface InterpretationVocabulary {
  readonly strength: readonly string[];
  readonly robustness: readonly string[];
  readonly evidence_group: readonly string[];
  readonly note: string;
}

export interface MetricsArtifact {
  readonly schema_version: string;
  readonly configuration: AnalyticalConfiguration;
  readonly global: GlobalMetrics;
  readonly series: Readonly<Record<SeriesId, SeriesMetrics>>;
  readonly countries: readonly CountryId[];
  readonly category_review: readonly CategoryReview[];
  readonly interpretation_vocabulary: InterpretationVocabulary;
}

// ---------------------------------------------------------------------------
// claims.json
// ---------------------------------------------------------------------------

export interface ClaimsSummary {
  readonly total: number;
  readonly by_disposition: Readonly<Record<string, readonly string[]>>;
  readonly by_status: Readonly<Record<string, readonly string[]>>;
  readonly requiring_citation: readonly string[];
  readonly unsourced_count: number;
}

export interface Claim {
  readonly id: string;
  /** Where the claim appears in the original project. */
  readonly origin: string;
  /** Verbatim original wording, kept so the correction is auditable. */
  readonly original_text: string;
  readonly status: ClaimStatus;
  readonly disposition: ClaimDisposition;
  readonly reason: string;
  /** Metric paths establishing the status. Empty when the data cannot speak. */
  readonly evidence: readonly string[];
  /** Draft replacement wording, or null. NOT published copy. */
  readonly suggested_statement: string | null;
  /** Citations. Empty means the claim may not be rendered as fact. */
  readonly sources: readonly string[];
  /** The gate: render as a factual statement only when true. */
  readonly publishable_as_fact: boolean;
}

export interface ClaimsArtifact {
  readonly schema_version: string;
  readonly summary: ClaimsSummary;
  readonly policy: {
    readonly unverifiable_external_claims: string;
    readonly publishable_rule: string;
  };
  readonly claims: readonly Claim[];
}

// ---------------------------------------------------------------------------
// manifest.json
// ---------------------------------------------------------------------------

export interface DataSource {
  readonly id: string;
  readonly name: string;
  readonly publisher: string;
  readonly url: string;
  /** Null for sources without a series identifier (Google Trends). */
  readonly series_id: string | null;
  readonly units: string;
  readonly frequency: string;
  readonly notes: string;
}

export interface ManifestArtifact {
  readonly schema_version: string;
  readonly pipeline_version: string;
  /** RFC 3339 UTC. The ONLY non-reproducible field in any artifact. */
  readonly generated_at: string;
  readonly _determinism_note: string;
  /** SHA-256 over the analytical artifacts. Compare two builds with this. */
  readonly content_hash: string;
  readonly sources: readonly DataSource[];
  readonly source_files: Readonly<Record<string, string>>;
  readonly artifacts: Readonly<Record<string, string>>;
  readonly coverage: Coverage;
  readonly analytical_configuration: ManifestAnalyticalConfiguration;
  readonly claims_summary: ClaimsSummary;
}

// ---------------------------------------------------------------------------
// Bundle
// ---------------------------------------------------------------------------

/** All five artifacts, validated. */
export interface ArtifactBundle {
  readonly panel: PanelArtifact;
  readonly countries: CountriesArtifact;
  readonly metrics: MetricsArtifact;
  readonly claims: ClaimsArtifact;
  readonly manifest: ManifestArtifact;
}

export type ArtifactName = keyof ArtifactBundle;

export const ARTIFACT_FILENAMES: Readonly<Record<ArtifactName, string>> = {
  panel: "panel.json",
  countries: "countries.json",
  metrics: "metrics.json",
  claims: "claims.json",
  manifest: "manifest.json",
};
