import { GeistMono } from "geist/font/mono";
import { GeistSans } from "geist/font/sans";
import type { Metadata } from "next";
import type { ReactNode } from "react";

import { AppShell } from "../src/components/layout/AppShell.tsx";

import "./globals.css";

/**
 * Product identity is fixed by docs/product-architecture.md §8. It names the
 * data, the scope and the period, and asserts no finding -- branding must not
 * claim a relationship the analysis does not support.
 */
export const metadata: Metadata = {
  title: "Global Oil Crisis vs EV Interest Analysis — 2026",
  description:
    "An interactive analysis of Brent crude prices and electric-car search interest " +
    "across five markets, 2025–2026.",
};

/**
 * Root layout: the document, the typeface, and nothing else.
 *
 * Everything that was inlined here in step 1 — the skip link, the header and the
 * footer — now lives in `AppShell` and the components it composes. The rule is
 * that this file describes the HTML document; the shell describes the product.
 * Step 1 deliberately inlined a rudimentary header and footer, and step 3's job
 * was to extract them rather than let this file keep growing.
 *
 * THE ONE THING THIS FILE OWNS BESIDES THE DOCUMENT: THE TYPEFACE
 *
 * `GeistSans.variable` and `GeistMono.variable` are class names generated by
 * `next/font/local` inside the `geist` package. Each one declares a single custom
 * property — `--font-geist-sans` and `--font-geist-mono` — whose value is the
 * hashed `@font-face` family Next emitted for the bundled `.woff2`, followed by
 * that face's metric-adjusted fallback. `tokens.css` §4 reads those two properties
 * and nothing else; no component names a family.
 *
 * They belong on `<html>` rather than on `<body>` for a concrete reason: `<html>`
 * IS `:root`, which is where `tokens.css` declares `--font-display`,
 * `--font-sans`, `--font-mono` and `--font-numeric`. A custom property set on
 * `<body>` would not be visible to a `var()` in a `:root` rule, so the tokens
 * would silently fall through to their fallback chain.
 *
 * The fonts are SELF-HOSTED FROM THE npm DEPENDENCY. The `.woff2` files live in
 * `node_modules/geist`, Next copies them into `/_next/static/media/` at build time
 * and serves them from this origin. No font file is committed to this repository,
 * nothing is installed at the operating-system level, and no request goes to
 * Google Fonts or any other third party. `e2e/typography.e2e.ts` asserts all three.
 */
export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" className={`${GeistSans.variable} ${GeistMono.variable}`}>
      <body className="flex min-h-dvh flex-col">
        <AppShell>{children}</AppShell>
      </body>
    </html>
  );
}
