import type { Metadata } from "next";

import { getArtifacts } from "../src/lib/artifacts.ts";

import "./globals.css";

/**
 * Product identity is fixed by docs/product-architecture.md §8. It names the
 * data, the scope and the period, and asserts no finding -- branding must not
 * claim a relationship the analysis does not support.
 */
export const metadata: Metadata = {
  title: "Global Oil Crisis vs EV Interest Analysis — 2026",
  description:
    "An interactive analysis of Brent crude prices and electric-car search interest " +
    "across five markets, 2025–2026.",
};

/**
 * Root layout: the `AppShell` foundation from docs/product-architecture.md §4.
 *
 * Implements the page-level half of the accessibility contract (§5): semantic
 * landmarks, a skip-to-content link, and a single `h1` owned by the page rather
 * than the shell. `Navigation` is intentionally absent -- it is step 3 of the
 * §10 implementation order, and an empty `<nav>` landmark would be worse for a
 * screen-reader user than no landmark at all.
 */
export default function RootLayout({ children }: { children: React.ReactNode }) {
  const { manifest } = getArtifacts();

  return (
    <html lang="en">
      <body className="min-h-dvh flex flex-col">
        {/* Visible only on focus. First tab stop on every page. */}
        <a
          href="#main-content"
          className="sr-only focus:not-sr-only focus:absolute focus:top-4 focus:left-4 focus:z-50 focus:rounded-md focus:border focus:border-border-strong focus:bg-surface focus:px-4 focus:py-2 focus:text-small focus:text-fg"
        >
          Skip to content
        </a>

        <header className="sticky top-0 z-40 border-b border-border bg-bg/95 backdrop-blur-sm">
          <div className="mx-auto flex max-w-page items-baseline justify-between gap-4 px-(--page-padding-inline) py-4">
            <span className="text-h4 font-medium tracking-tight text-fg">
              Oil Prices <span className="text-fg-subtle">vs</span> EV Interest
            </span>
            <span className="text-meta text-fg-muted">2025–2026</span>
          </div>
        </header>

        <main id="main-content" className="flex-1">
          {children}
        </main>

        <footer className="mt-(--section-spacing) border-t border-border">
          <div className="mx-auto max-w-page px-(--page-padding-inline) py-8">
            <h2 className="text-label uppercase text-fg-muted">Sources</h2>
            <ul className="mt-3 flex flex-col gap-2">
              {manifest.sources.map((source) => (
                <li key={source.id} className="text-meta text-fg-secondary">
                  <a
                    href={source.url}
                    className="underline decoration-border-strong underline-offset-2 hover:decoration-fg-muted"
                    rel="noreferrer noopener"
                    target="_blank"
                  >
                    {source.publisher} — {source.name}
                  </a>
                  {source.series_id !== null ? (
                    <span className="numeric text-fg-muted"> ({source.series_id})</span>
                  ) : null}
                </li>
              ))}
            </ul>
            <p className="mt-6 text-meta text-fg-muted">
              Analytical artifacts generated by the project pipeline, version{" "}
              <span className="numeric">{manifest.pipeline_version}</span>. Content hash{" "}
              <span className="numeric">{manifest.content_hash.slice(0, 16)}</span>.
            </p>
          </div>
        </footer>
      </body>
    </html>
  );
}
