import type { DataSource } from "../../data/index.ts";
import { Container } from "./Container.tsx";

interface FooterProps {
  /** `manifest.sources[]`. Never a hard-coded URL. */
  readonly sources: readonly DataSource[];
  readonly pipelineVersion: string;
  readonly contentHash: string;
}

/**
 * Attribution and provenance.
 *
 * Every source is read from `manifest.sources[]`, so the credit list cannot drift
 * from the data that was actually used. The pipeline version and content hash are
 * shown because reproducibility is a claim this project makes: two builds of the
 * same analysis share a content hash, and a reader can check it.
 *
 * `SourceNote` (docs/product-architecture.md §4) is step 4. When it exists, the
 * list below is what it is extracted from — the component boundary is already in
 * the right place, so that will be a move rather than a rewrite.
 */
export function Footer({ sources, pipelineVersion, contentHash }: FooterProps) {
  return (
    <footer className="mt-(--section-spacing) border-t border-border">
      <Container width="page" className="py-8">
        <h2 className="text-label uppercase text-fg-muted">Sources</h2>
        <ul className="mt-3 flex flex-col gap-2">
          {sources.map((source) => (
            <li key={source.id} className="text-meta text-fg-secondary">
              <a
                href={source.url}
                className="rounded-xs underline decoration-border-strong underline-offset-2 transition-colors duration-(--duration-fast) ease-out hover:decoration-fg-muted"
                rel="noreferrer noopener"
                target="_blank"
              >
                {source.publisher} — {source.name}
              </a>
              {source.series_id !== null ? (
                <span className="numeric text-fg-muted"> ({source.series_id})</span>
              ) : null}
            </li>
          ))}
        </ul>
        <p className="mt-6 text-meta text-fg-muted">
          Analytical artifacts generated by the project pipeline, version{" "}
          <span className="numeric">{pipelineVersion}</span>. Content hash{" "}
          <span className="numeric">{contentHash.slice(0, 16)}</span>.
        </p>
      </Container>
    </footer>
  );
}
