import type { DataSource } from "../../data/index.ts";
import { SourceNote } from "../content/SourceNote.tsx";
import { Container } from "./Container.tsx";

interface FooterProps {
  /** `manifest.sources[]`. Never a hard-coded URL. */
  readonly sources: readonly DataSource[];
  readonly pipelineVersion: string;
  readonly contentHash: string;
}

/**
 * Attribution and provenance.
 *
 * STEP 4 CHANGED ONE THING HERE
 * The source list moved into `SourceNote` and this component composes it. That was
 * always the plan (product-architecture.md §4 names `SourceNote` as its own
 * component) and step 3 left the boundary in the right place, so it was a move
 * rather than a rewrite. The footer keeps what is genuinely its own: the width
 * container, the top border, the rhythm, and the provenance line.
 *
 * The pipeline version and content hash are shown because reproducibility is a
 * claim this project makes: two builds of the same analysis share a content hash,
 * and a reader can check it.
 */
export function Footer({ sources, pipelineVersion, contentHash }: FooterProps) {
  return (
    <footer className="mt-(--section-spacing) border-t border-border">
      <Container width="page" className="py-8">
        <SourceNote sources={sources} />
        <p className="mt-6 text-meta text-fg-muted">
          Analytical artifacts generated by the project pipeline, version{" "}
          <span className="numeric">{pipelineVersion}</span>. Content hash{" "}
          <span className="numeric">{contentHash.slice(0, 16)}</span>.
        </p>
      </Container>
    </footer>
  );
}
